version: '3.8'

services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: air-quality-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: air_quality
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - air-quality-network
    restart: unless-stopped

  # Redis 缓存
  redis:
    image: redis:7.0-alpine
    container_name: air-quality-redis
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    networks:
      - air-quality-network
    restart: unless-stopped

  # 空气质量监测应用
  air-quality-server:
    build: .
    container_name: air-quality-server
    ports:
      - "8082:8080"
      - "1883:1883"
    environment:
      - CONFIG_FILE=config/config.docker.yaml
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=admin
      - DB_NAME=air_quality
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    depends_on:
      - mysql
      - redis
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    networks:
      - air-quality-network
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:

networks:
  air-quality-network:
    driver: bridge
