services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: air-quality-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: air_quality
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - air-quality-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis 缓存
  redis:
    image: redis:7.0-alpine
    container_name: air-quality-redis
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    networks:
      - air-quality-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 3s
      retries: 5

  # 空气质量监测应用
  app:
    build: .
    image: air-quality-server:latest
    container_name: air-quality-server
    ports:
      - "8082:8080"  # Web服务端口
      - "1883:1883"  # MQTT端口
    environment:
      - AIR_QUALITY_CONFIG=/app/config/config.docker.yaml
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=admin
      - DB_NAME=air_quality
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    depends_on:
      - mysql
      - redis
    # volumes:
      # - ./config:/app/config  # 移除卷映射，使用容器内配置文件
      # - ./logs:/app/logs      # 移除卷映射，日志输出到容器内
    networks:
      - air-quality-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  mysql_data:
  redis_data:

networks:
  air-quality-network:
    driver: bridge
