# 空气质量监测系统 - Docker环境配置文件

# 服务器配置
server:
  port: 8080
  host: "0.0.0.0"  # Docker容器内需要监听所有接口
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 120

# 数据库配置
database:
  host: "mysql"  # Docker服务名
  port: 3306
  username: "root"
  password: "admin"
  database: "air_quality"
  charset: "utf8mb4"
  max_idle: 10
  max_open: 100
  max_life: 3600

# Redis配置
redis:
  host: "redis"  # Docker服务名
  port: 6379
  password: ""  # 开发环境无密码
  db: 0
  pool_size: 10

# MQTT配置
mqtt:
  broker: "0.0.0.0:1883"  # 容器内MQTT服务
  client_id: "air-quality-server"
  keep_alive: 60
  qos: 1
  clean_session: true
  auto_reconnect: true
  connect_timeout: 30

# JWT配置
jwt:
  secret: "air-quality-docker-secret-key-change-in-production"
  expire_hours: 24
  issuer: "air-quality-server"

# 日志配置
log:
  level: "info"
  format: "json"
  output: "stdout"  # Docker环境输出到stdout
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: true

# 服务配置
service:
  name: "air-quality-server"
  version: "1.0.0"
  environment: "docker"
  debug: false

# 告警配置
alert:
  enabled: true
  thresholds:
    pm25:
      warning: 35
      critical: 75
    pm10:
      warning: 50
      critical: 150
    formaldehyde:
      warning: 0.05
      critical: 0.1
    co2:
      warning: 1000
      critical: 2000
    temperature:
      warning: 30
      critical: 35
    humidity:
      warning: 80
      critical: 90

# 数据存储配置
storage:
  retention_days: 30
  cleanup_interval: 24  # 小时
  batch_size: 1000
